#ENC[AES256_GCM,data:Orts4HyL2qVG1PBUwY8hPn8soAWDnOZLMNesS36FCm+iBgytpjkoe5TUOlgEDiqqBvV5kGqeNw==,iv:YmUsBj7EfTixSLLXT1ufC6hsSabZCdRiHdvAmxrWWUk=,tag:7aNqDsokZDUzjOAiRYzidQ==,type:comment]
#ENC[AES256_GCM,data:6rnSUINzEliYS5oP0TbZNqXlK6x+NI3z98sKHoZH6yC8WwYx+f4OTX5UMI7+fe1Vs3aGj59l5eqI/UH30xTgwnPwn8plghmX2Q==,iv:yWvDqyO0uHKEN8Jw2qpI17wlYH/V+DGxjiGE0Z28gfY=,tag:p77hnpQ706JL71YG718Olg==,type:comment]
NPM_TOKEN: ENC[AES256_GCM,data:Ud0QbeMHcAv13nTuRWfx266jdZt05gFe3mnUDYuEmrFZjUh2JPD7Gg==,iv:M+dN7M8e3zGpEdPymPsuvDaT/2VtJG8XoK2kkSyBseU=,tag:nUuovYE/WcGdaH4o4gxIog==,type:str]
CIRCLECI_TOKEN: ENC[AES256_GCM,data:ViXs2IwlVbNDywzIrvKBbmxO300LczDcBgTvVIde9xKOPITEFAJt69MPu8jKCY0jtnJOCVCd5NGaXrwk8KPGkqV59MWVwA==,iv:8/FaQToVCi9+EcB9k0tST8srHm4bDlGUyjKegzXaN74=,tag:PqvNBLJw7wUNAxwtfPZkfg==,type:str]
CLICKUP_TICKET_SKILL_TOKEN: ENC[AES256_GCM,data:0kWCqyiC1rJ74HFO0HT680vIfJQyjlCcsASKizntL+4n6zuBJtXouHShUw==,iv:kpqY32yFM67jAMxRgGXEn0o2rqWtMHirLwG36Rcr2qM=,tag:KpI+wguzodWFND9cjZn+fQ==,type:str]
sops:
    age:
        - recipient: age1dgz8fae897a6eslwdgw226t9pze8u84cl2u73s7l0lxmgqrxc9qqqsr9f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YkJ3disrQytOQ1Fqb3hu
            S3VQSHIxVEEzdy9wKzhzVnhJMFg1L2JaQjFFCmtJMG9GclpXOVF2TFlJeFhpRlcz
            SFg2NERHNktyaGJSNFdmQXE1eDloZncKLS0tIE5makFrWVpQWER4QWt4a1VyQnNN
            RitTRHVhcWdGZE5jQmYrRUJBU3R0RkkK5jKzFEjzqfMvmRqtbAwHVKWCBTPift/S
            5A9+CpCyrB+7SVuWD4yXamrjqRWBSwFimRUr7KEd0KzErM7NFMeQoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T21:46:07Z"
    mac: ENC[AES256_GCM,data:0lDnUwcTMYEq0OK4OA/9jnveASXwsy2qnprTbD3lbbWp2liJCXsBC3GGVD+acpfWLyJHAcPIIomkOwA7OWsfxwx+rGeaQTtLdbqXzsZ2i8JJ0Dj3eeeOnS5ecqUC/4jzFKYGZebsHDyCp4Tg2qKAnsPjWG932CTYAYJdIMq784w=,iv:T3xt3txrZ55lPGprsfJ0kYeUq6yvRzxb/MUA8BTrzPU=,tag:pO4NCZ/8drQ6EqWBkxpk7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
