#ENC[AES256_GCM,data:Orts4HyL2qVG1PBUwY8hPn8soAWDnOZLMNesS36FCm+iBgytpjkoe5TUOlgEDiqqBvV5kGqeNw==,iv:YmUsBj7EfTixSLLXT1ufC6hsSabZCdRiHdvAmxrWWUk=,tag:7aNqDsokZDUzjOAiRYzidQ==,type:comment]
#ENC[AES256_GCM,data:6rnSUINzEliYS5oP0TbZNqXlK6x+NI3z98sKHoZH6yC8WwYx+f4OTX5UMI7+fe1Vs3aGj59l5eqI/UH30xTgwnPwn8plghmX2Q==,iv:yWvDqyO0uHKEN8Jw2qpI17wlYH/V+DGxjiGE0Z28gfY=,tag:p77hnpQ706JL71YG718Olg==,type:comment]
NPM_TOKEN: ENC[AES256_GCM,data:wly9BGhUHtS2zm0t6exP0L2NfgjEc7bZyltJ8+WjfwSJ8nZClCQsPA==,iv:KQtJPCGtwcMVUe5ki3Zg7YiSLAulcsAkCRUPOF7mlgs=,tag:Vm5BSTOX6kdXKmx4jpRMlw==,type:str]
CIRCLECI_TOKEN: ENC[AES256_GCM,data:ViXs2IwlVbNDywzIrvKBbmxO300LczDcBgTvVIde9xKOPITEFAJt69MPu8jKCY0jtnJOCVCd5NGaXrwk8KPGkqV59MWVwA==,iv:8/FaQToVCi9+EcB9k0tST8srHm4bDlGUyjKegzXaN74=,tag:PqvNBLJw7wUNAxwtfPZkfg==,type:str]
sops:
    age:
        - recipient: age1dgz8fae897a6eslwdgw226t9pze8u84cl2u73s7l0lxmgqrxc9qqqsr9f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YkJ3disrQytOQ1Fqb3hu
            S3VQSHIxVEEzdy9wKzhzVnhJMFg1L2JaQjFFCmtJMG9GclpXOVF2TFlJeFhpRlcz
            SFg2NERHNktyaGJSNFdmQXE1eDloZncKLS0tIE5makFrWVpQWER4QWt4a1VyQnNN
            RitTRHVhcWdGZE5jQmYrRUJBU3R0RkkK5jKzFEjzqfMvmRqtbAwHVKWCBTPift/S
            5A9+CpCyrB+7SVuWD4yXamrjqRWBSwFimRUr7KEd0KzErM7NFMeQoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T20:41:38Z"
    mac: ENC[AES256_GCM,data:MifullnqgQuiJj5qlGo0hg3lNEO5erN1h9agtwxGaMTvGlCkgPafXrcpsGZcSYGmWih2ZCam+NMAQfLOXlh8wtVtTSwP1SuKQhyt+8TRlhylU8Y7H9gpNzWV2NOJWXGbiGSHM7viUgl7LQkoh2tnXxxZkhRl57kyyJkogJZHMAE=,iv:Y9mYpIAtGHE2Pma5Bj0SVBirXIzvCLC7CbzJuelvvbY=,tag:787bomDmmQ9Co5AOeHXyYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
